Chapter05no
Hikarussk/training.frontend pull request #13
Opened 2017-04-12 09:51 UTC by Hikarussk

2017-04-12 10:24 UTC, gkoyama requested changes
口頭で説明した、階層の練習(86,87ページあたり)を追加してくださいね。

2017-04-13 01:21 UTC, gkoyama commented on HTML.CSS/01.Basic/chapter05/c05-05-a.html
> +    .float-=clear {
記述ミス
イコール(=)

2017-04-13 01:26 UTC, gkoyama commented
これはまだ途中ですか？
途中ならタイトルの頭に[WIP]をつけてください。
あと、全体的にインデントが無くなっていたり、正しく修正されていたりする変更がありますので見直してくださいね。

2017-04-13 02:49 UTC, Hikarussk commented
確認ミスです。
終わったものだと思っていました。
あとで修正しておきます。失礼いたしました。

2017-04-13 05:40 UTC, Hikarussk commented on HTML.CSS/01.Basic/chapter05/c05-05-a.html
> +    .float-clear {
タイプミスを修正いたしました

2017-04-17 11:40 UTC, gkoyama approved these changes
OKです
OKですが、インデントが付いてなかったり位置が違ったりしているので次回からは丁寧に書きましょう。

2017-04-18 01:31 UTC, merged