Chapter05 2
Hikarussk/training.frontend pull request #17
Opened 2017-04-14 05:42 UTC by Hikarussk

2017-04-14 08:39 UTC, gkoyama commented on HTML.CSS/01.Basic/chapter05/about/index.html
> +<p><a href="./access.html">アクセスマップ</a></p>
同階層なら./いらないんじゃないかな？

2017-04-14 08:42 UTC, Hikarussk commented on HTML.CSS/01.Basic/chapter05/about/index.html
> +<p><a href="./access.html">アクセスマップ</a></p>
分かりやすいかな、と思って付けてました。
不要であれば書かないようにしますね

2017-04-14 08:58 UTC, gkoyama commented on HTML.CSS/01.Basic/chapter05/c05-03-a.html
> +<img src="../images/image1646.jpg" width="904" height="572" alt="日が沈む">
『日が沈む』文言が違います

2017-04-14 09:00 UTC, Hikarussk commented on HTML.CSS/01.Basic/chapter05/c05-03-a.html
> +<img src="../images/image1646.jpg" width="904" height="572" alt="日が沈む">
陽ですね。失礼致しました。

2017-04-14 09:05 UTC, gkoyama requested changes
下記の修正お願いします。
・同階層なら./は不必要
・日→陽
・全体的にインデントがない

2017-04-14 09:18 UTC, Hikarussk reviewed
### 修正内容
- 誤字の修正(日→陽)
- インデントの見直し
- ファイル参照方法の変更(./→無)

2017-04-14 09:18 UTC, Hikarussk commented on HTML.CSS/01.Basic/chapter05/about/index.html
> +<p><a href="access.html">アクセスマップ</a></p>
ファイル参照方法を変えました

2017-04-14 09:18 UTC, Hikarussk commented on HTML.CSS/01.Basic/chapter05/c05-03-a.html
> +<img src="../images/image1646.jpg" width="904" height="572" alt="陽が沈む">
誤字修正しました

2017-04-14 09:18 UTC, Hikarussk commented on HTML.CSS/01.Basic/chapter05/c05-03-b.html
> +<img src="../images/image1646.jpg" width="904" height="572" alt="陽が沈む" class="img-responsive">
誤字修正しました

2017-04-14 09:18 UTC, Hikarussk commented on HTML.CSS/01.Basic/chapter05/c05-03-c.html
> +    <img src="../images/image1646.jpg" width="904" height="572" alt="陽が沈む" class="img-responsive">
誤字修正しました

2017-04-18 01:31 UTC, gkoyama approved these changes
OKです！
こちらマージしてください！

2017-04-18 01:31 UTC, merged