Advanced
Hikarussk/training.frontend pull request #20
Opened 2017-04-24 06:33 UTC by Hikarussk

### Advancedのソースコード

2017-04-24 06:53 UTC, gkoyama commented on HTML.CSS/02.Advanced/index.html
> +    © sample site
コピーライトのhtml5での正しい記述方法を調べてみましょ！

2017-04-24 06:57 UTC, gkoyama requested changes
コメントしました。
あと、全体的にコピペし過ぎかな？
すべてのタグ、属性、クラス名を自分で考えていてる(聞かれても説明できる)のが望ましいですよ！

2017-04-24 06:57 UTC, gkoyama commented on HTML.CSS/02.Advanced/index.html
> +<div class="header-inner">
このdivの必要な意味は？

2017-04-24 06:59 UTC, Hikarussk commented on HTML.CSS/02.Advanced/index.html
> +<div class="header-inner">
自分で作成したhtmlフォーマットのタグです。消し忘れました。

2017-04-24 07:00 UTC, Hikarussk commented on HTML.CSS/02.Advanced/index.html
> +    © sample site
<p><small>&copy; コピーライト名</small></p>
ですね、覚えました！

2017-04-24 10:07 UTC, gkoyama commented
勘違いして伝わっているかもしれなので念の為確認ですが、お手本通りというのはデザインを見て自分でコードを書くことであって、demoページのコードを見ながらお手本にしてはダメですよ。
あと、途中の場合はタイトルにWIPをつけてくださいね！

2017-04-25 00:43 UTC, Hikarussk commented
すみません、取れるところは取って作業してました。
確かにオリジナルでやらないと意味ないですね。
気をつけます。

2017-05-02 05:22 UTC, gkoyama approved these changes
LGTM!
OKです！

2017-05-02 05:22 UTC, merged